configfile: "../../config/config.yaml"

## Read lists
import pandas as pd
df = pd.read_csv(config["list_MUSE_ISTAGHarmonized"])
LIST_HMUSE_NAMES = df.Name.tolist()

###################################
## Function definitions

###################################
## Rules
rule ALL:
    #input:"../../data/SurrealGAN/prep/SurrealGAN_testISTAG.csv"
    #input:"../../data/SurrealGAN/prep/SurrealGAN_NatureMed_train.csv"
    #input:"../../data/SurrealGAN/data/SurrealGAN_NatureMed_train_demog.csv"
    #input:"../../data/SurrealGAN/data/SurrealGAN_ISTAG_test_demog.csv"
    input:"../../data/SurrealGAN/model/SurrealGAN_NatureMed/converged_model_fold2"
    
#################################    
## Prep data

rule select_sample:
    '''
    Select surrealgan sample
    '''
    input:
        sample="../../data/samples/SurrealGAN/sample_SurrealGAN_{stype}.csv",
        data="../../data/ISTAG_Data/init_csv/istaging_v1.2_selvars.csv",
        rois="../../config/list_MUSE_ISTAGHarmonizedSingle.csv",
    params:
        vars='MRID,Age,Sex,DX_Binary,DLICV_baseline,participant_id,Diagnosis',
    output:
        "../../data/SurrealGAN/prep/SurrealGAN_{stype}.csv"
    resources:
        mem_mb=8000
    shell:
        "echo python utils/util_select_sample.py {input} {params} {output}; "
        "python utils/util_select_sample.py {input} {params} {output}"

rule prep_surrealgan_data:
    '''
    Split input data into demog and roi files
    '''
    input:
        "../../data/SurrealGAN/prep/SurrealGAN_{stype}.csv",
    output:
        demog="../../data/SurrealGAN/data/SurrealGAN_{stype}_demog.csv",
        roi="../../data/SurrealGAN/data/SurrealGAN_{stype}_rois.csv",
    resources:
        mem_mb=8000
    shell:
        "echo python utils/util_prep_surrealgan_data.py {input} {output}; "
        "python utils/util_prep_surrealgan_data.py {input} {output}"

#################################    
## Run training

rule smilegan_train_folds:
    '''
    Train SurrealGAN model
    '''
    input:
        demog="../../data/SurrealGAN/data/SurrealGAN_{stype}_train_demog.csv",
        roi="../../data/SurrealGAN/data/SurrealGAN_{stype}_train_rois.csv",
    output:
        "../../data/SurrealGAN/model/SurrealGAN_{stype}/converged_model_fold{fold}"
    params:
        npattern = '4',
        final_saving_epoch = '63000',
        fold="{fold}",
        numfold='50',
    resources:
        mem_mb=16000
    shell:
        "echo bash ./utils/util_surrealgan_train_folds.sh {input} {params} {output}; " 
        "bash ./utils/util_surrealgan_train_folds.sh {input} {params} {output}" 
        
rule SurrealGAN_test:
    '''
    Test SurrealGAN model using the split test sample
    '''
    input:
        data="../../data/SurrealGAN/s{stype}/r{rtype}/data/NiChart_DLMUSE_{dtype}_test.csv",
        mdl="../../data/SurrealGAN/s{stype}/r{rtype}/models/NiChart_DLMUSE_{dtype}_model.pkl.gz"
    output:
        csv="../../data/SurrealGAN/s{stype}/r{rtype}/pred/NiChart_DLMUSE_{dtype}_pred.csv"
    resources:
        mem_mb=16000
    shell:
        "echo spare_score -a test -i {input.data} -m {input.mdl} -o {output.csv}; "
        "spare_score -a test -i {input.data} -m {input.mdl} -o {output.csv}"

rule SurrealGAN_eval:
    '''
    Evaluate accuracy on test sample
    '''
    input:
        data="../../data/SurrealGAN/s{stype}/r{rtype}/data/NiChart_DLMUSE_{dtype}_test.csv",
        pred="../../data/SurrealGAN/s{stype}/r{rtype}/pred/NiChart_DLMUSE_{dtype}_pred.csv"
    output:
        csv="../../data/SurrealGAN/s{stype}/r{rtype}/pred/NiChart_DLMUSE_{dtype}_eval.csv"
    resources:
        mem_mb=8000
    shell:
        "echo python utils/util_eval_spare.py {input} {wildcards.stype} {output}; "
        "python utils/util_eval_spare.py {input} {wildcards.stype} {output}"

#rule copy_model:
    #'''
    #Copy model to models folder
    #'''
    #input:
        #"../../data/SurrealGAN/s_{stype}/models/NiChart_DLMUSE_{dtype}_model.pkl.gz"
    #output:
        #"../../models/SurrealGAN/SurrealGAN_{stype}_NiChart_DLMUSE_{dtype}_model.pkl.gz"
    #shell:
        #"cp {input} {output}"
