
configfile: "../../config/config.yaml"

## Read lists
import pandas as pd
df = pd.read_csv(config["list_MUSE_ISTAGHarmonized"])
LIST_HMUSE_NAMES = df.Name.tolist()

###################################
## Function definitions

###################################
## Rules
rule ALL:
    #input:"../../data/ISTAG_Data/SmileGAN/ISTAG_HMUSE_trainADNI2_BL.csv"
    #input:"../../data/ISTAG_Data/init_csv/istaging_v1.2_all.csv"
    #input:"../../data/ISTAG_Data/init_csv/istaging_v1.2_mri.csv"
    input:"../../data/ISTAG_Data/init_csv/istaging_v1.2_selvars.csv"
    
#################################    
## Prep data

#ruleorder: pkl_to_csv > filter_mri

rule pkl_to_csv:
    '''
    Convert pkl file to csv
    '''
    input:
        "../../data/ISTAG_Data/ISTAGING_Data_Consolidation_2020/{version}/istaging.pkl.gz"
    output:
        "../../data/ISTAG_Data/init_csv/istaging_{version}_all.csv"
    resources:
        mem_mb=8000
    shell:
        "echo python utils/util_pkl_to_csv.py {input} {output}; "
        "python utils/util_pkl_to_csv.py {input} {output} "

rule filter_mri:
    '''
    Select only mri data
    '''
    input:
        "../../data/ISTAG_Data/init_csv/istaging_{version}_all.csv"
    output:
        "../../data/ISTAG_Data/init_csv/istaging_{version}_mri.csv"
    resources:
        mem_mb=8000
    shell:
        "echo python utils/util_filter_mri.py {input} {output}; "
        "python utils/util_filter_mri.py {input} {output} "

rule sel_vars:
    '''
    Select only main variables
    '''
    input:
        "../../data/ISTAG_Data/init_csv/istaging_{version}_mri.csv"
    output:
        "../../data/ISTAG_Data/init_csv/istaging_{version}_selvars.csv"
    resources:
        mem_mb=8000
    shell:
        "echo python utils/util_sel_vars.py {input} {output}; "
        "python utils/util_sel_vars.py {input} {output} "
