## Config file
configfile: "../../config/config_Genetics.yaml"

###################################
## Out file names

OUT_CONFIG = expand("../../data/{dir_output}/config/{cname}", cname = ["config_Genetics.yaml", "list_MUSE_all.csv"], dir_output = config["dir_output"])

OUT_RESULTS = expand("../../data/{dir_output}/make_bed/ukb_chr{chrno}", chrno = ['1', '2', '3'],  dir_output = config["dir_output"])

OUT_FILES = OUT_CONFIG + OUT_RESULTS

#print("Target out files:" + '\n' + '\n'.join(OUT_FILES) + '\n')

###################################
## Rules

rule ALL:
    '''
    First rule: lists the final expected out files
    '''
    input: OUT_FILES

rule copy_config:
    '''
    Rule for copying config files to output dir
    '''
    input:
        "../../config/{cname}"
    output:
        expand("../../data/{dir_output}/config/{{cname}}", dir_output = config["dir_output"])
    shell:
        "cp -v {input} {output}"

rule make_bed:
    '''
    Apply make_bed
    '''
    input:
        in_bgen=expand("../../data/{dir_input}/Imputation_BGEN/ukb22828_c{{chrno}}_b0_v3.bgen", dir_input = config["dir_input"]), 
        in_sample=expand("../../data/{dir_input}/Imputation_Sample/ukb22828_c{{chrno}}_b0_v3_s487253.sample", dir_input = config["dir_input"])
    params:
        flagref = config["flagref"],
        maf = config["maf"],
        geno = '0.03',
        hwe = '1e-10',
        mind = '0.03',
        rmdup = 'force-first',
        flagmbed = '1'
    output:
        "../../data/{dir_output}/make_bed/ukb_chr{chrno}"
    resources:
        mem_mb=8000
    shell:
        "bash ./utils/util_make_bed.sh {input} {wildcards.chrno} {params} {output}"
