
configfile: "../../config/config.yaml"

## Read lists
import pandas as pd

df = pd.read_csv(config["list_studies"])
LIST_STUDIES = df.Study.tolist()

df = pd.read_csv(config["list_rois_primary"])
LIST_ROIS = df.Index.tolist()

###################################
## Function definitions

###################################
## Rules
rule ALL:
    #input:"../../data/harmonization/hISTAG/NiChart_DLMUSE_raw_rsingleROI_train.csv"
    #input:"../../data/SurrealGAN_NatMed/prep/data_mAging-NatMed_train.csv"
    #input:"../../data/SurrealGAN_NatMed/prep/_DLMUSE_selrois.csv"
    #input:"../../data/SurrealGAN_NatMed/prep/Study1_selvars.csv"
    input:"../../data/SurrealGAN_NatMed/model/combatModel_mAging-NatMed.pkl.gz"

#################################  
## Prepare test data for harmonization

rule rename_muse_rois:
    '''
    Rename DLMUSE roi indices to roi names
    '''
    input:
        "../../data/SurrealGAN_NatMed/Input_StudyData/{study}_MUSE.csv",
    params:
        prefix = 'MUSE_Volume_'
    output:
        "../../data/SurrealGAN_NatMed/prep/{study}_MUSE.csv"
    resources:
        mem_mb=8000
    shell:
        "echo python utils/util_add_prefix.py {input} {params} {output}; "
        "python utils/util_add_prefix.py {input} {params} {output}"

rule merge_data:
    '''
    Merge demog data to DLMUSE ROIs
    '''
    input:
        demog="../../data/SurrealGAN_NatMed/Input_StudyData/{study}_Demog.csv",
        data="../../data/SurrealGAN_NatMed/prep/{study}_MUSE.csv",
    params:
        key_var = 'MRID'
    output:
        "../../data/SurrealGAN_NatMed/prep/{study}_datainit.csv"
    resources:
        mem_mb=8000
    shell:
        "echo python utils/util_merge_data.py {output} {params} {input}; "
        "python utils/util_merge_data.py {output} {params} {input}"

rule select_vars:
    '''
    Select input rois
    '''
    input:
        data="../../data/SurrealGAN_NatMed/prep/{study}_datainit.csv",
        rois="../../config/list_MUSE_ISTAGSingle.csv",
    output:
        "../../data/SurrealGAN_NatMed/prep/{study}_selvars.csv"
    params:
        vars = 'MRID,Age,Sex,SITE'
    resources:
        mem_mb=8000
    shell:
        "echo python utils/util_select_vars.py {input} {params} {output}; "
        "python utils/util_select_vars.py {input} {params} {output}"


#################################    
## Prepare reference data for harmonization

rule select_ref_harmonization:
    '''
    Select harmonization sample
    '''
    input:
        sample="../../data/samples/SurrealGAN/sample_SurrealGAN_{stype}_train.csv",
        data="../../data/ISTAG_Data/init_csv/istaging_v1.2_selvars.csv",
        rois="../../config/list_MUSE_ISTAGHarmonizedSingle.csv",
    params:
        vars='MRID,Age,Sex,DLICV',
    output:
        "../../data/SurrealGAN_NatMed/prep/dataInit_{stype}.csv"
    resources:
        mem_mb=8000
    shell:
        "echo python utils/util_select_sample.py {input} {params} {output}; "
        "python utils/util_select_sample.py {input} {params} {output}"

rule edit_ref_harmonization:
    '''
    Edit harmonization sample
    ## FIXME: SurrealGAN model was trained on harmonized MUSE
    ##        Before applying the model we harmonize the new set to harmonized data
    ##        considering it a single set
    '''
    input:
        "../../data/SurrealGAN_NatMed/prep/dataInit_{stype}.csv"
    output:
        "../../data/SurrealGAN_NatMed/prep/data_{stype}.csv"
    resources:
        mem_mb=8000
    shell:
        "echo python utils/util_edit_harmonization_sample.py {input} {output}; "
        "python utils/util_edit_harmonization_sample.py {input} {output}"

#################################    
## Harmonization

rule combat_train:
    '''
    Train combat harmonization model
    '''    
    input:
        "../../data/SurrealGAN_NatMed/prep/data_{stype}.csv"
    params:
        batch='SITE',
        vkey='MRID',
        vnum='DLICV',
        vcat='Sex',
        vspline='Age'
    output:
        mdl="../../data/SurrealGAN_NatMed/model/combatModel_{stype}.pkl.gz",
        csv="../../data/SurrealGAN_NatMed/model/combatModel_{stype}_combatOut.csv"
    resources:
        mem_mb=16000
    shell:
        "echo neuroharm -a learn -i {input} -k {params.vkey} -b {params.batch} "
        "-n {params.vnum} -c {params.vcat} -s {params.vspline} -o {output.mdl} -u {output.csv}; "
        #"neuroharm -a learn -i {input} -k {params.vkey} -b {params.batch} "
        "-n {params.vnum} -c {params.vcat} -s {params.vspline} -o {output.mdl} -u {output.csv}"
        "neuroharm -a learn -i {input} -k {params.vkey} -b {params.batch} "
        "-n {params.vnum} -c {params.vcat} -c {params.vspline} -o {output.mdl} -u {output.csv}"

rule combat_test:
    '''
    Apply combat harmonization model to calculate harmonized values
    '''    
    input:
        data="../../data/SurrealGAN_NatMed/prep/{study}_selvars.csv",
        mdl="../../data/SurrealGAN_NatMed/model/combatModel_{stype}.pkl.gz"
    output:
        "../../data/SurrealGAN_NatMed/harmonized/{study}_{stype}_combatOut.csv"
    resources:
        mem_mb=16000
    shell:
        "echo neuroharm -a apply -i {input.data} -m {input.mdl} -u {output.csv};"
        "neuroharm -a apply -i {input.data} -m {input.mdl} -u {output.csv}"

#################################    
## SurrealGAN
