
localrules: reorientLPS

import pandas as pd
df = pd.read_csv('../../data/MUSETest/Lists/IDList.csv')
DICT_BLID = dict(zip(df['MRID'], df['BLID']))
LIST_MRID = list(DICT_BLID.keys())
##BLIDS = ['OAS30001_MR_d0129', 'OAS30002_MR_d0371']


rule ALL:
    #input:expand("../../data/{study}/Protocols/MUSE_4D/{mrid}/{mrid}_T1_LPS_N4_brain_muse-ss_Mean_fastbc_muse.nii.gz", study = ['MUSETest'], mrid = ['OAS30001_MR_d0129'])
    input:expand("../../data/{study}/Protocols/Skull-Stripped/{mrid}/{mrid}_T1_LPS_N4_brainmask_muse-ss.nii.gz", study = ['MUSETest'], mrid = ['OAS30001_MR_d0129'])

rule reorientLPS:
    """
    Reorient a 3D image to LPS orientation
    """
    input:
        "../../data/{study}/Data/RenamedNifti/{mrid}/{mrid}_{mod}.nii.gz"
    output:
        "../../data/{study}/Protocols/ReOrientedLPS/{mrid}/{mrid}_{mod}_LPS.nii.gz"
    resources:
        mem_mb=8000,
    shell:
        "bash ./utils/util_reorientLPS.sh {input} {output}"

rule biascorr_N4:
    """
    N4 bias correction
    """
    input:
        "../../data/{study}/Protocols/ReOrientedLPS/{mrid}/{mrid}_{mod}_LPS.nii.gz"
    output:
        "../../data/{study}/Protocols/BiasCorrected/{mrid}/{mrid}_{mod}_LPS_N4.nii.gz"
    resources:
        mem_mb=8000,
    shell:
        "bash ./utils/util_biascorr_N4.sh {input} {output}"

rule bmask_MUSE:
    """
    MUSE skull stripping
    - Applied to all images, both BL and FU
    """
    input:
        fin="../../data/{study}/Protocols/BiasCorrected/{mrid}/{mrid}_T1_LPS_N4.nii.gz",
        cont="../../resources/Container/CBICApipeline_centos7.sif"
    output:
        "../../data/{study}/Protocols/Skull-Stripped/{mrid}/{mrid}_T1_LPS_N4_brainmask_muse-ss.nii.gz",
    resources:
        mem_mb=32000
    shell:
        "bash ./utils/util_bmask_MUSE_singularity_wrapper.sh {input} {output}"

rule bmask_MUSE_4D:
    """
    Use baseline MUSE bmasks to calculate 4D bmask
    - Applied to all images both BL and FU
    - For BL images an image is warped to itself to calculate the 4D mask; this looks redundant
    """
    input:
        img="../../data/{study}/Protocols/BiasCorrected/{mrid}/{mrid}_T1_LPS_N4.nii.gz",
        mask="../../data/{study}/Protocols/Skull-Stripped/{mrid}/{mrid}_T1_LPS_N4_brainmask_muse-ss.nii.gz",
        blimg = lambda wildcards : "../../data/{study}/Protocols/BiasCorrected/" + DICT_BLID[wildcards.mrid] + "/" + DICT_BLID[wildcards.mrid] + "_T1_LPS_N4.nii.gz",
        blmask = lambda wildcards : "../../data/{study}/Protocols/Skull-Stripped/" + DICT_BLID[wildcards.mrid] + "/" + DICT_BLID[wildcards.mrid] + "_T1_LPS_N4_brainmask_muse-ss.nii.gz"
    #params:
        #blid=lambda wildcards:DICT_BLID[wildcards.mrid]
    output:
        "../../data/{study}/Protocols/Skull-Stripped_4D/{mrid}/{mrid}_T1_LPS_N4_brain_muse-ss_Mean.nii.gz"
    resources:
        mem_mb=8000
    shell:
        "bash ./utils/util_bmask_MUSE_4D.sh {input} {output}"

rule bmask_T1T2:
    """
    T2 based skull stripping
    """
    input:
        t1="../../data/{study}/Protocols/BiasCorrected/{mrid}/{mrid}_T1_LPS_N4.nii.gz",
        t2="../../data/{study}/Protocols/BiasCorrected/{mrid}/{mrid}_T2_LPS_N4.nii.gz",
        bmask="../../data/{study}/Protocols/Skull-Stripped_4D/{mrid}/{mrid}_T1_LPS_N4_brain_muse-ss_Mean.nii.gz"
    output:
        "../../data/{study}/Protocols/Skull-Stripped_T2/{mrid}/{mrid}_T1_LPS_N4_brainmask_muse-ss_Mean_ICV.nii.gz"
    resources:
        mem_mb=8000,
    shell:
        "bash ./utils/util_bmask_T1T2.sh {input} {output}"

rule biascorr_FAST:
    """
    FAST bias correction
    """
    input:
        "../../data/{study}/Protocols/Skull-Stripped_4D/{mrid}/{mrid}_T1_LPS_N4_brain_muse-ss_Mean.nii.gz"
    output:
        "../../data/{study}/Protocols/fastbc/{mrid}/{mrid}_T1_LPS_N4_brain_muse-ss_Mean_fastbc.nii.gz"
    resources:
        mem_mb=8000,
    shell:
        "bash ./utils/util_biascorr_FAST.sh {input} {output}"
        
rule MUSE_BL:
    """
    Run MUSE; applied only to BL images
    """
    input:
        "../../data/{study}/Protocols/fastbc/{mrid}/{mrid}_T1_LPS_N4_brain_muse-ss_Mean_fastbc.nii.gz"
    output:
        "../../data/{study}/Protocols/MUSE_BL/{mrid}/{mrid}_{mod}_LPS_N4_brain_muse-ss_Mean_fastbc_muse.nii.gz"
    resources:
        mem_mb=8000,
    shell:
        "bash ./utils/util_MUSE.sh {input} {output}"

rule MUSE_4D:
    """
    Run MUSE using BL warps 
    - Applied to all images both BL and FU
    - For BL images an image is warped to itself to calculate the 4D ROIs; this looks redundant    
    """
    input:
        img="../../data/{study}/Protocols/fastbc/{mrid}/{mrid}_T1_LPS_N4_brain_muse-ss_Mean_fastbc.nii.gz",
        blimg = lambda wildcards: "../../data/{study}/Protocols/fastbc/" + DICT_BLID[wildcards.mrid] + "/" + DICT_BLID[wildcards.mrid] + "_T1_LPS_N4_brain_muse-ss_Mean_fastbc.nii.gz",
        blseg = lambda wildcards: "../../data/{study}/Protocols/MUSE_BL/" + DICT_BLID[wildcards.mrid] + "/" + DICT_BLID[wildcards.mrid] + "_T1_LPS_N4_brain_muse-ss_Mean_fastbc_muse.nii.gz"
    params:
        BLID=lambda wildcards:DICT_BLID[wildcards.mrid]
    output:
        "../../data/{study}/Protocols/MUSE_4D/{mrid}/{mrid}_T1_LPS_N4_brain_muse-ss_Mean_fastbc_muse.nii.gz"
    resources:
        mem_mb=8000
    shell:
        "bash ./utils/util_MUSE_4D.sh {input} {output} {wildcards.mrid} {params.BLID}"
        
