version: Genetics_ukbb
dir_input: InitData_UKBB-Genetic/genetic_202107
dir_output: Genetics/UKBB-Genetic-Processed
flagref: 1
maf: 0.01
geno: 0.03
hwe: 1e-10 
ming: 0.03
rmdup: force-first
flagmbed: 1
