list_rois_all: ../../config/list_MUSE_allROI.csv
list_rois_single: ../../config/list_MUSE_singleROI.csv
list_rois_composite: ../../config/list_MUSE_compositeROI.csv
list_rois_primary: ../../config/list_MUSE_primaryROI.csv
list_rois_short: ../../config/list_MUSE_shortROI.csv
list_studies: ../../config/list_studies.csv
list_SPARE: ../../config/list_SPARE-models.csv
list_demog_normalization: ../../config/list_demog_normalization.csv
list_MUSE_ISTAGHarmonized: ../../config/list_MUSE_ISTAGHarmonized.csv
